export default {
  CHANNEL_CALL: 'CHANNEL_CALL',
  CHANNEL_DETAILS: 'CHANNEL_DETAILS',
  CHANNEL_MEMBERS: 'CHANNEL_MEMBERS',
  CHANNEL_SETTINGS: 'CHANNEL_SETTINGS',
  NOTIFICATION_BUTTON: 'NOTIFICATION_BUTTON',
};
