export default {
  ACTIVITY: 'ACTIVITY',
  CHANNEL_CALL: 'CHANNEL_CALL',
  CHANNEL_DETAILS: 'CHANNEL_DETAILS',
  CHANNEL_MEMBERS: 'CHANNEL_MEMBERS',
  CHANNEL_SETTINGS: 'CHANNEL_SETTINGS',
  MORE: 'MORE',
  NOTIFICATION_BUTTON: 'NOTIFICATION_BUTTON',
  STARRED: 'STARRED',
};
